version: '3.8'

services:
  api:
    build: .
    ports:
      - "${PRO_APP_PORT}:${PRO_APP_PORT}"
    environment:
      - NODE_ENV=prod
      - PRO_APP_PORT=${PRO_APP_PORT}
      - PRO_DB_HOST=mongodb
      - PRO_DB_PORT=${PRO_DB_PORT}
      - PRO_DB_NAME=${PRO_DB_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - backend-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: